name: Unit Test

on:
  push:
    branches: ["main"]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Do something
        run: |
          echo "foo" 
